version: '3.9'

services:
  nuxt:
    container_name: nuxt3-sb-container
    build: .
    ports:
      - '3000:3000'
      - '6006:6006'
      - '24678:24678'
    tty: true
    volumes:
      - .:/app
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
